CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK(role IN ('admin','viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive email uniqueness/lookup, replacing SQLite's
-- `UNIQUE ... COLLATE NOCASE`. The plain UNIQUE above still exists for
-- exact-match FK/PK-style lookups; this index is what create_user/
-- get_user_by_email actually rely on.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (lower(email));

CREATE TABLE IF NOT EXISTS connected_accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    platform TEXT NOT NULL CHECK(platform IN ('youtube','instagram','tiktok')),
    account_label TEXT NOT NULL,
    external_account_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    token_expiry TEXT,
    scopes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, platform, external_account_id)
);

CREATE INDEX IF NOT EXISTS idx_connected_accounts_user ON connected_accounts(user_id, platform);

-- Created before `runs` (only references users/connected_accounts) so
-- runs.batch_id can reference it inline below with no forward-reference
-- problem - Postgres validates REFERENCES targets at CREATE TABLE time,
-- unlike SQLite which never checks this at DDL time regardless of order.
CREATE TABLE IF NOT EXISTS run_batches (
    batch_id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    youtube_account_id TEXT REFERENCES connected_accounts(id),
    topic TEXT NOT NULL,
    target_platforms TEXT NOT NULL,
    videos_count INTEGER NOT NULL,
    clips_per_video INTEGER NOT NULL,
    stagger_gap_minutes INTEGER NOT NULL,
    requested_privacy TEXT,
    status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running','succeeded','failed')),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ
);

-- Created before `runs` for the same reason (runs.schedule_id references
-- it). Its own last_run_id -> runs(run_id) is the one genuine circular
-- reference in this schema (runs.schedule_id -> scheduled_topics.id, and
-- scheduled_topics.last_run_id -> runs.run_id) - that one FK is added via
-- a guarded ALTER TABLE further down, once `runs` exists.
CREATE TABLE IF NOT EXISTS scheduled_topics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    youtube_account_id TEXT REFERENCES connected_accounts(id),
    topic TEXT NOT NULL,
    recurrence TEXT NOT NULL DEFAULT 'once' CHECK(recurrence IN ('once','daily')),
    scheduled_time TIMESTAMPTZ,
    daily_time TEXT,
    target_platforms TEXT NOT NULL DEFAULT 'youtube',
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','cancelled','completed')),
    last_triggered_at TIMESTAMPTZ,
    last_run_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_schedules_status ON scheduled_topics(status);
CREATE INDEX IF NOT EXISTS idx_schedules_user ON scheduled_topics(user_id);

CREATE TABLE IF NOT EXISTS runs (
    run_id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    youtube_account_id TEXT REFERENCES connected_accounts(id),
    topic TEXT NOT NULL,
    trigger_source TEXT NOT NULL CHECK(trigger_source IN ('cli','web','scheduled')),
    schedule_id INTEGER REFERENCES scheduled_topics(id),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','succeeded','failed')),
    current_stage TEXT,
    dry_run BOOLEAN NOT NULL DEFAULT false,
    requested_privacy TEXT,
    effective_privacy TEXT,
    target_platforms TEXT NOT NULL DEFAULT 'youtube',
    source_video_id TEXT,
    source_video_title TEXT,
    source_video_url TEXT,
    segment_start_s REAL,
    segment_end_s REAL,
    segment_score REAL,
    clip_path TEXT,
    metadata_title TEXT,
    metadata_description TEXT,
    metadata_hashtags TEXT,
    error_message TEXT,
    work_dir TEXT,
    batch_id TEXT REFERENCES run_batches(batch_id),
    scheduled_upload_at TIMESTAMPTZ,
    source_type TEXT,
    video_rank INTEGER,
    clip_rank INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_runs_status_created ON runs(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_runs_batch ON runs(batch_id);
CREATE INDEX IF NOT EXISTS idx_runs_scheduled_upload ON runs(scheduled_upload_at);
CREATE INDEX IF NOT EXISTS idx_runs_user ON runs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_batches_user ON run_batches(user_id, created_at DESC);

-- The one genuine forward reference: scheduled_topics.last_run_id -> runs,
-- added only once `runs` exists. Guarded with a catalog check (rather than
-- unsupported `ADD CONSTRAINT IF NOT EXISTS` syntax) so re-running this
-- file on every app boot - which init_db() does - stays a no-op here.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'scheduled_topics_last_run_id_fkey'
    ) THEN
        ALTER TABLE scheduled_topics
            ADD CONSTRAINT scheduled_topics_last_run_id_fkey
            FOREIGN KEY (last_run_id) REFERENCES runs(run_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS run_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    stage TEXT NOT NULL,
    message TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_run_events_run ON run_events(run_id, id);

CREATE TABLE IF NOT EXISTS run_uploads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    platform TEXT NOT NULL CHECK(platform IN ('youtube','instagram','tiktok')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','uploading','succeeded','failed','skipped')),
    video_id TEXT,
    url TEXT,
    privacy_status TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    UNIQUE(run_id, platform)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
